variable "aws_region" {
  type        = string
  description = "AWS region to deploy into."
  default     = "us-east-1"
}

variable "project_name" {
  type        = string
  description = "Short name used to prefix/tag all resources."
  default     = "hr-portal"
}

# --- Safety-critical: DO NOT set a default here ---------------------
# The API has NO authentication as of this deployment. If this were
# accidentally defaulted to 0.0.0.0/0, the ALB would expose the entire
# HR dataset (names, employment data, everything the API serves) to the
# open internet with zero access control. Leaving this required with no
# default means `terraform plan`/`apply` HARD-FAILS until it's set
# explicitly — it cannot be silently left open by omission.
#
# Set to your office/VPN CIDR, e.g. "203.0.113.4/32" for a single IP or
# "203.0.113.0/24" for a range. See DEPLOYMENT.md for how to set this
# safely (terraform.tfvars, gitignored) and the constraint it enforces.
variable "allowed_cidr" {
  type        = string
  description = "CIDR block allowed to reach the ALB (office/VPN only). The API has no authentication yet — this must never be 0.0.0.0/0."

  validation {
    condition     = var.allowed_cidr != "0.0.0.0/0"
    error_message = "allowed_cidr must not be 0.0.0.0/0 — the API has no authentication yet and this would expose it to the entire internet. Use your office/VPN CIDR instead."
  }
}

# --- Required for the GitHub OIDC trust policies in iam_github_oidc.tf ---
# hr-portal-api and hr-portal-frontend are separate GitHub repos with
# their own CD workflows (cd.yml in each), so each gets its own deploy
# role, scoped to only its own ECR repo + ECS service. Never wildcard
# these, and never let one repo's role reach the other's resources.
variable "github_repo_backend" {
  type        = string
  description = "GitHub \"org/repo\" for the hr-portal-api backend, e.g. \"my-org/hr-portal-api\"."
}

variable "github_repo_frontend" {
  type        = string
  description = "GitHub \"org/repo\" for the hr-portal-frontend frontend, e.g. \"my-org/hr-portal-frontend\"."
}

variable "create_github_oidc_provider" {
  type        = bool
  description = "Whether to create the GitHub Actions OIDC identity provider. AWS allows only one provider per issuer URL per account — set this to false if token.actions.githubusercontent.com is already registered (e.g. by another repo's Terraform)."
  default     = true
}

variable "github_deploy_branch" {
  type        = string
  description = "Branch the CD deploy role's trust policy is scoped to (matches cd.yml's trigger branch)."
  default     = "main"
}

# --- Database ---------------------------------------------------------
variable "db_name" {
  type    = string
  default = "hr_portal"
}

variable "db_username" {
  type        = string
  description = "Master DB username. The password is generated by Terraform (random_password) and stored only in Secrets Manager — never set it here."
  default     = "hr_portal_app"
}

variable "db_instance_class" {
  type        = string
  description = "Single instance, not Multi-AZ — acceptable cost/reliability tradeoff for an internal tool's first production deployment. Revisit (db.t4g.small+, multi_az=true) if uptime requirements grow."
  default     = "db.t4g.micro"
}

variable "db_allocated_storage_gb" {
  type    = number
  default = 20
}

variable "db_engine_version" {
  type    = string
  default = "8.0"
}

# --- ECS sizing ---------------------------------------------------------
# Small fixed sizes and desired_count=1 per service — an internal tool at
# this scale doesn't need headroom for burst traffic or HA across AZs.
# Bump desired_count to 2 first if you need zero-downtime deploys /
# resilience to a single task crashing.
variable "backend_container_port" {
  type    = number
  default = 8080
}

variable "frontend_container_port" {
  type    = number
  default = 8080
}

variable "backend_cpu" {
  type    = number
  default = 256
}

variable "backend_memory" {
  type    = number
  default = 512
}

variable "frontend_cpu" {
  type    = number
  default = 256
}

variable "frontend_memory" {
  type    = number
  default = 512
}

variable "desired_count" {
  type    = number
  default = 1
}

# --- Bootstrapping ---------------------------------------------------
# The very first `terraform apply` has to register ECS task definitions
# pointing at SOME image tag before any image has ever been pushed by
# CD. ":latest" won't exist in ECR yet either on a brand-new repo — the
# ECS service will sit in a failed-to-start loop until the first CD run
# pushes real images. This is expected; see DEPLOYMENT.md's first-time
# setup steps (apply, then manually trigger CD once).
variable "container_image_tag" {
  type    = string
  default = "latest"
}

# --- Future HTTPS (not implemented in this pass) ---------------------
# Left as an explicit empty-string TODO rather than silently omitted, so
# it's obvious this was a deliberate deferral, not an oversight. Once a
# domain is decided: request/validate an ACM cert, set this var to its
# ARN, and add an HTTPS listener (443) + redirect the HTTP listener to
# it in alb.tf.
variable "acm_certificate_arn" {
  type        = string
  description = "TODO: ACM certificate ARN for HTTPS, once a domain exists. Empty = HTTP-only via the ALB's default DNS name (current state)."
  default     = ""
}
